CREATE TABLE VENDOR(
    ID      INT PRIMARY KEY,
    EMAIL  VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME    VARCHAR(255) NOT NULL,
    STREET   VARCHAR(255) NOT NULL,
    CITY     VARCHAR(255) NOT NULL,
    STATE    VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL
);